version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install zip gzip tar
      - wget https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip
      - unzip terraform_0.11.4_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
        
  build:
    commands:
      - terraform init -input=false 
      - terraform plan -out=tfplan -input=false
      - terraform apply -input=false tfplan